server:
  port: 8888

elastic:
  job:
    zk:
      namespace: eslatic-job
      server-lists: 39.106.154.120:2181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/broker_message
    username: root
    password: root

logging:
  level:
    root: debug